name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    assemble:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Assemble core
              run: "./gradlew core:assemble"
            - name: Assemble desktop
              run: "./gradlew desktop:assemble"
