name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    assemble:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Invoke gradle
              run: "./gradlew desktop:assemble"
