name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    autobuild:
        runs-on: ubuntu-latest
        container: openjdk:20-jdk
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Assemble core
              run: "./gradlew core:assemble"
            - name: Assemble desktop
              run: "./gradlew desktop:assemble"
    unittests:
        runs-on: ubuntu-latest
        needs: autobuild
        container: openjdk:20-jdk
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run tests
              run: "./gradlew core:test"
